URL: http://10.10.120.3
log:
    backup: 3
    level: DEBUG
    pattern: '%(log_color)s%(bg_white)s%(asctime)s%(levelname)-8s%(reset)s %(message)s'
    output: 2
TL_LOG: /webgui/log/
RESERVE_REPORTS_NUM: 3
EMAIL_SERVER: smtp.163.com
EMAIL_USR: 670662282@qq.com
EMAIL_RECEIVE: a670662282@163.com

MAIL_TITLE: 'UI自动化测试报告'
IMP_TIME: 20
TIME_OUT: 30
