sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install --dev --skip-lock
script:
  - pipenv run python setup.py install
  - pipenv run coverage run --source=pyselenium -m unittest discover
after_success:
  - pipenv run coveralls
