result = {'details': [{'in_out': {'in': {}, 'out': {}},
              'name': 'testcase description',
              'records': [{'attachment': '',
                           'name': 'get token',
                           'response_time': '78.95',
                           'status': 'success'}],
              'stat': {'errors': 0,
                       'expectedFailures': 0,
                       'failures': 0,
                       'skipped': 0,
                       'successes': 1,
                       'total': 1,
                       'unexpectedSuccesses': 0},
              'success': True,
              'time': {'duration': 0.09774899482727051,
                       'start_at': 1553839119.249368}}],
 'platform': {'httprunner_version': '2.0.5',
              'platform': 'Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic',
              'python_version': 'CPython 3.6.6'},
 'stat': {'testcases': {'fail': 0, 'success': 1, 'total': 1},
          'teststeps': {'errors': 0,
                        'expectedFailures': 0,
                        'failures': 0,
                        'skipped': 0,
                        'successes': 1,
                        'total': 1,
                        'unexpectedSuccesses': 0}},
 'success': True,
 'time': {'duration': 0.09774899482727051,
          'start_at': 1553839119.249368,
          'start_datetime': '2019-03-29 05:58:39'}}


x={'details': [{'in_out': {'in': {}, 'out': {}},
              'name': 'testcase description',
              'records': [{'attachment': '',
                           'meta_datas': {'data': [{'request': {'headers': {'Accept': '*/*',
                                                                            'Accept-Encoding': 'gzip, '
                                                                                               'deflate',
                                                                            'Connection': 'keep-alive',
                                                                            'Content-Length': '0',
                                                                            'User-Agent': 'python-requests/2.18.4'},
                                                                'method': 'POST',
                                                                'url': 'http://oauth.nxgvm.com/oauth/credit/token?app_id=814a2e2c6af44d4ebf91365e18d75217&secret=e7284af1ba94e8ba87930d2914dd3568&grant_type=client_credential'},
                                                    'response': {'content_type': 'application/json;charset=utf-8',
                                                                 'cookies': {},
                                                                 'encoding': 'utf-8',
                                                                 'headers': {'Access-Control-Allow-Credentials': 'true',
                                                                             'Access-Control-Allow-Headers': 'x-requested-with',
                                                                             'Access-Control-Allow-Methods': 'POST, '
                                                                                                             'GET, '
                                                                                                             'OPTIONS, '
                                                                                                             'DELETE',
                                                                             'Access-Control-Allow-Origin': '*',
                                                                             'Access-Control-Max-Age': '3600',
                                                                             'Connection': 'keep-alive',
                                                                             'Content-Length': '100',
                                                                             'Content-Type': 'application/json;charset=utf-8',
                                                                             'Date': 'Fri, '
                                                                                     '29 '
                                                                                     'Mar '
                                                                                     '2019 '
                                                                                     '05:39:22 '
                                                                                     'GMT',
                                                                             'Server': 'nginx/1.13.12',
                                                                             'X-Ratelimit-Limit': '0',
                                                                             'X-Ratelimit-Remaining': '0',
                                                                             'X-Ratelimit-Reset': '0'},
                                                                 'json': {'code': 0,
                                                                          'msg': 'Success.',
                                                                          'result': {'access_token': '6CCJDDQIOEC7WHO35CZOOFVDEI',
                                                                                     'expires_in': 7200}},
                                                                 'ok': True,
                                                                 'reason': 'OK',
                                                                 'status_code': 200,
                                                                 'url': 'http://oauth.nxgvm.com/oauth/credit/token?app_id=814a2e2c6af44d4ebf91365e18d75217&secret=e7284af1ba94e8ba87930d2914dd3568&grant_type=client_credential'}}],
                                          'name': 'get token',
                                          'stat': {'content_size': 100,
                                                   'elapsed_ms': 74.894,
                                                   'response_time_ms': 78.95},
                                          'validators': [{'check': 'status_code',
                                                          'check_result': 'pass',
                                                          'check_value': 200,
                                                          'comparator': 'eq',
                                                          'expect': 200},
                                                         {'check': 'content.code',
                                                          'check_result': 'pass',
                                                          'check_value': 0,
                                                          'comparator': 'eq',
                                                          'expect': 0}]},
                           'meta_datas_expanded': [{'data': [{'request': {'headers': {'Accept': '*/*',
                                                                                      'Accept-Encoding': 'gzip, '
                                                                                                         'deflate',
                                                                                      'Connection': 'keep-alive',
                                                                                      'Content-Length': '0',
                                                                                      'User-Agent': 'python-requests/2.18.4'},
                                                                          'method': 'POST',
                                                                          'url': 'http://oauth.nxgvm.com/oauth/credit/token?app_id=814a2e2c6af44d4ebf91365e18d75217&secret=e7284af1ba94e8ba87930d2914dd3568&grant_type=client_credential'},
                                                              'response': {'content_type': 'application/json;charset=utf-8',
                                                                           'cookies': {},
                                                                           'encoding': 'utf-8',
                                                                           'headers': {'Access-Control-Allow-Credentials': 'true',
                                                                                       'Access-Control-Allow-Headers': 'x-requested-with',
                                                                                       'Access-Control-Allow-Methods': 'POST, '
                                                                                                                       'GET, '
                                                                                                                       'OPTIONS, '
                                                                                                                       'DELETE',
                                                                                       'Access-Control-Allow-Origin': '*',
                                                                                       'Access-Control-Max-Age': '3600',
                                                                                       'Connection': 'keep-alive',
                                                                                       'Content-Length': '100',
                                                                                       'Content-Type': 'application/json;charset=utf-8',
                                                                                       'Date': 'Fri, '
                                                                                               '29 '
                                                                                               'Mar '
                                                                                               '2019 '
                                                                                               '05:39:22 '
                                                                                               'GMT',
                                                                                       'Server': 'nginx/1.13.12',
                                                                                       'X-Ratelimit-Limit': '0',
                                                                                       'X-Ratelimit-Remaining': '0',
                                                                                       'X-Ratelimit-Reset': '0'},
                                                                           'json': {'code': 0,
                                                                                    'msg': 'Success.',
                                                                                    'result': {'access_token': '6CCJDDQIOEC7WHO35CZOOFVDEI',
                                                                                               'expires_in': 7200}},
                                                                           'ok': True,
                                                                           'reason': 'OK',
                                                                           'status_code': 200,
                                                                           'url': 'http://oauth.nxgvm.com/oauth/credit/token?app_id=814a2e2c6af44d4ebf91365e18d75217&secret=e7284af1ba94e8ba87930d2914dd3568&grant_type=client_credential'}}],
                                                    'name': 'get token',
                                                    'stat': {'content_size': 100,
                                                             'elapsed_ms': 74.894,
                                                             'response_time_ms': 78.95},
                                                    'validators': [{'check': 'status_code',
                                                                    'check_result': 'pass',
                                                                    'check_value': 200,
                                                                    'comparator': 'eq',
                                                                    'expect': 200},
                                                                   {'check': 'content.code',
                                                                    'check_result': 'pass',
                                                                    'check_value': 0,
                                                                    'comparator': 'eq',
                                                                    'expect': 0}]}],
                           'name': 'get token',
                           'response_time': '78.95',
                           'status': 'success'}],
              'stat': {'errors': 0,
                       'expectedFailures': 0,
                       'failures': 0,
                       'skipped': 0,
                       'successes': 1,
                       'total': 1,
                       'unexpectedSuccesses': 0},
              'success': True,
              'time': {'duration': 0.09774899482727051,
                       'start_at': 1553839119.249368}}],
 'platform': {'httprunner_version': '2.0.5',
              'platform': 'Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic',
              'python_version': 'CPython 3.6.6'},
 'stat': {'testcases': {'fail': 0, 'success': 1, 'total': 1},
          'teststeps': {'errors': 0,
                        'expectedFailures': 0,
                        'failures': 0,
                        'skipped': 0,
                        'successes': 1,
                        'total': 1,
                        'unexpectedSuccesses': 0}},
 'success': True,
 'time': {'duration': 0.09774899482727051,
          'start_at': 1553839119.249368,
          'start_datetime': '2019-03-29 05:58:39'}}
